#!/bin/bash
###
# Docker start script
#
# Change the --name to your liking, but this may kill future scripts
###
docker run -d \
    --name swarmbot \
    --restart on-failure:5 \
    -v "/var/docker/swarmbot/docs:/var/docs" \
    --env-file ./env.list \
    registry.gitlab.com/crunchyintheory/swarmbot
